#include "Node.h"
void populate(Node *current);
void recursivearithmetic(Node *current);
int main()
{
    std::ofstream generatedunittest("autogeneratedtest.py");
    // prompt name of head item
    std::cout << "Name of Linked List:" << std::endl;
    std::string headname = "";
    std::getline(std::cin, headname);
    auto head = new Node(headname);
    populate(head);
    recursivearithmetic(head);
    // cleanup and terminate process
    NodeUtility::generatateunittest(head, generatedunittest);
    NodeUtility::destroy(head);
    return 0;
}
void populate(Node *current)
{
    std::cout << "What ingredients do you need to create " << current->ingredient << ":" << std::endl;
    //create input loop
}
void recursivearithmetic(Node *current)
{
}
